# Generated by Django 4.2.6 on 2023-10-16 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JewelryHouseWebsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JewelryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('weight', models.FloatField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Ring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter', models.FloatField()),
                ('size', models.FloatField()),
                ('amount', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JewelryHouseWebsite.jewelryproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Necklace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField()),
                ('amount', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JewelryHouseWebsite.jewelryproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Earring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('amount', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JewelryHouseWebsite.jewelryproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Clock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sizeofFace', models.FloatField()),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('amount', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JewelryHouseWebsite.jewelryproduct')),
            ],
        ),
    ]
